ambiente = 3

#Produ\u00c3\u00a7\u00c3\u00a3o
xmlDir = //192.168.2.193/XMLs/NFCe
urlDB = jdbc:oracle:thin:@192.168.2.3:1521/dbsenior
userDB = sapiens
passwordDB = sbresapiens
urlSdeWS = http://192.168.2.193:8989/SDE/Integracao
wsUser = edocs
wsPassword = r3m0t0-

#Teste 3
xmlDir3 = //192.168.2.40/xml/NFCe
urlDB3 = jdbc:oracle:thin:@192.168.2.4:1521/dbsenior
userDB3 = sapiensteste3
passwordDB3 = sbresapiensteste3
urlSdeWS3 = http://srv-spnsteste3:8989/SDE/Integracao
wsUser3 = edocs
wsPassword3 = r3m0t0-
